#!/bin/bash

set -euEo pipefail

PATH="/usr/local/opt/coreutils/libexec/gnubin/:${PATH}"
export PATH

echo '::set-env name=DOCKER_BUILDKIT::1'

echo "::set-env name=build_rfc3339::$(date --rfc-3339=seconds)"

head -n 10 Dockerfile |
  perl -n -e 'print "::set-env name=build_", lc($1), "::$2\n" if m/^#\s+(Authors|title|Description):\s*(.*)\s*$/i;'

# EOF
