name: ci

on:
  schedule:
    - cron: "53 9 * * 3"
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Checkout
        uses: actions/checkout@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Environment variables
        run: script/ci-env

      - name: Run Buildx
        run: |
          docker buildx build \
            "--platform=linux/amd64" \
            "--output=type=image,push=false" \
            "--file=Dockerfile" \
            "--label=org.opencontainers.image.title=${{ env.build_title }}" \
            "--label=org.opencontainers.image.description=${{ env.build_description }}" \
            "--label=org.opencontainers.image.authors=${{ env.build_authors }}" \
            "--label=org.opencontainers.image.created=${{ env.build_rcf3339 }}" \
            "--label=org.opencontainers.image.url=https://github.com/${{ github.repository }}" \
            "--label=org.opencontainers.image.source=https://github.com/${{ github.repository }}.git#${{ github.ref }}" \
            "--label=org.opencontainers.image.revision=${{ github.sha }}" \
            "./"
